# .github/workflows/main.yml
name: kubernetes CI/CD
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: checkout source code
      uses: actions/checkout@main

    - name: Build the Docker image
      run: docker build . -t $GITHUB_ACTOR/app:$GITHUB_RUN_NUMBER

    - name: Test image
      run: docker run --entrypoint /test $GITHUB_ACTOR/app:$GITHUB_RUN_NUMBER

    - name: login
      run: docker login -u $GITHUB_ACTOR -p $PASSWORD
      env:
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: push
      run: docker push $GITHUB_ACTOR/app:$GITHUB_RUN_NUMBER

    - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: '.'

        # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
        # Default: '.'
        cwd: '.'

        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default:
        default_author: github_actor

        # The message for the commit
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Your commit message'
        
